### ISSUE TITLE
Is the nailgun C client up to date?

### ISSUE THREAD

**Issue by jvican** [facebook/nailgun#116]
I wonder if the nailgun C client is up to date. If it's not, I guess it's better to remove it? If it is, what's the difference between using the C client and the python one?

**Comment by sbalabanov** [comment]
@jvican you are always welcome to come up with integration test. People use python client with python programs, c client with cpp programs.

**Comment by jvican** [comment]
Alright, I'll take that as "it should be up to date" :smile:. Would help on this front but this it's not relevant to my use case.
