### ISSUE TITLE
No tag for Nailgun 0.9.3?

### ISSUE THREAD

**Issue by Duhemm** [facebook/nailgun#119]
I noticed that there's no tag for Nailgun 0.9.3 (nor for 0.9.2, by the way).

Is there a reason for not pushing tags along with the releases?

**Comment by sbalabanov** [comment]
we did not push it to package repos yet

**Comment by cvogt** [comment]
tags would still be nice :)

**Comment by sbalabanov** [comment]
https://github.com/facebook/nailgun/releases/tag/nailgun-all-0.9.3
