### ISSUE TITLE
How to properly terminate the nail?

### ISSUE THREAD

**Issue by rrzaripov** [facebook/nailgun#133]
I'm runnning [storescp](https://github.com/dcm4che/dcm4che/tree/master/dcm4che-tool/dcm4che-tool-storescp) tool from dcm4che project. This utility work as server - listen some port in infinite loop and interupted by pressing CTRL+C keys. But how shutdown it in nailgun? I'm trying to close transport, but nail still work. Sending CTRL+C via stdin also not work. Thank you in advance for any help.

**Comment by sbalabanov** [comment]
Do you want to terminate the nail or nailgun (server)?
- For nail, you subscribe nail's code to client's event with NGContext.addClientListener (example: https://github.com/facebook/buck/blob/dcbc69700809ac65519abf0ed34e58cf8e5b78f0/src/com/facebook/buck/cli/Main.java#L1332) and upon receiving a termination signal, handle it properly with nails' code, for example interrupting the running thread.
- For nailgun, you just send `ng-stop` command

**Comment by rrzaripov** [comment]
I need terminate nail, so adding listener into nail code perhaps the best way to do it. Thank for code example!
