### ISSUE TITLE
Publish 0.9.3 artifacts to a public repository

### ISSUE THREAD

**Issue by mjeffryes** [facebook/nailgun#150]
There are several projects using nailgun that still depend on the 0.9.1 version because that is the only version with published artifacts in a public repository (https://mvnrepository.com/artifact/com.martiansoftware/nailgun-server/0.9.1/usages). 

Since the 0.9.1 server does not support the 0.9.3 stdin mode, projects still depending on 0.9.1 are somewhat broken for people using the latest client (eg. homebrew-core installs 0.9.3 client by default since Feb 2018)

Publishing artifacts for the 0.9.3 server would enable the community to move consistently to the latest version.

**Comment by sbalabanov** [comment]
We are going to deploy a new version (under com.facebook.nailgun namespace) and publish it to public. Please stay tuned :)

**Comment by sbalabanov** [comment]
https://search.maven.org/artifact/com.facebook/nailgun-all/1.0.0/pom
