### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by dwightguth** [facebook/nailgun#177]
It's been over a year since the last release, and almost half a year since I submitted some changes upstream in the hopes of maybe someday being able to use the canonical version of nailgun in my project (https://github.com/kframework/k).

Can you provide some indication when the next release might be? I'd like to be able to try it out, and that's going to be a lot easier if something is released and deployed on Maven Central.

**Comment by philipjameson** [comment]
Hey @dwightguth , 1.0.1 has been pushed. Give us a shout if you have any problems!
