### ISSUE TITLE
Publish new maven artifact nailgun-server 0.9.2

### ISSUE THREAD

**Issue by usrflo** [facebook/nailgun#40]
There were some bugfixes since December 2012 (maven artifact version 0.9.1). It would be great if you could publish 0.9.2 now. Thank you.

**Comment by rgwilton** [comment]
+1 for me as well please.

**Comment by balihoo-gens** [comment]
+1. We use the NGClientListener functionality; it would be great to have that in maven

**Comment by archenroot** [comment]
+1

**Comment by balihoo-jmelanson** [comment]
+1

**Comment by teppeis** [comment]
+1

**Comment by mpetazzoni** [comment]
@martylamb Any chance to see this happen soon? Would be great to get a 0.9.2 artifact available on a public Maven repo.

**Comment by jvican** [comment]
Can we close? It's been quite some time since this was requested.
