### ISSUE TITLE
possible data race on NGServer.serversocket

### ISSUE THREAD

**Issue by yilongli** [facebook/nailgun#63]
Again, we got this race report when testing the [K framework](https://github.com/kframework/k):

```
Data race on field com.martiansoftware.nailgun.NGServer.serversocket: {{{
    Concurrent read in thread T1 (locks held: {})
 ---->  at com.martiansoftware.nailgun.NGServer.getPort(NGServer.java:384)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:74)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.main.Main.runApplication(Main.java:99)
        at org.kframework.main.Main.main(Main.java:51)
    T1 is the main thread

    Concurrent write in thread T13 (locks held: {})
 ---->  at com.martiansoftware.nailgun.NGServer.run(NGServer.java:413)
    T13 is created by T1
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:72)
}}}
```

It says the assignment [`serversocket = new ServerSocket(port, 0, addr)`](https://github.com/martylamb/nailgun/blob/master/nailgun-server/src/main/java/com/martiansoftware/nailgun/NGServer.java#L413) and the return statement [`return ((serversocket == null) ? port : serversocket.getLocalPort());`](https://github.com/martylamb/nailgun/blob/master/nailgun-server/src/main/java/com/martiansoftware/nailgun/NGServer.java#L384) are in a data race. I think it's sufficient to declare `serversocket` as volatile.

**Comment by sbalabanov** [comment]
Closing all issues older than 6 months; please reopen if it is still relevant
