### ISSUE TITLE
recv: Connection reset by peer

### ISSUE THREAD

**Issue by akhodakivskiy** [facebook/nailgun#68]
I'm getting this messages on the client side _after_ my job finishes. What might cause this?

`recv: Connection reset by peer`

This happens on third or fourth time I send the same nail to the server. First couple runs are usually clean.

I use nailgun to run time and memory consuming jobs. The reason to use nailgun is to share memory between the jobs that takes a while to bootstrap. The jobs are multi-threaded. 

The job is silent until it's finished. At the end it prints the result in just one line using `Console.out.println` (it's in Scala). I noticed that if I print another line, then it won't be passed over to the client. i.e. something will happen between printing to the std out.

**Comment by sbalabanov** [comment]
Closing all issues older than 6 months; please reopen if it is still relevant
