### ISSUE TITLE
Significant slowdown and possible increased memory usage since df35649

### ISSUE THREAD

**Issue by dwightguth** [facebook/nailgun#77]
We created a fork of commit df35649 some time ago in order to add a few pieces of functionality missing in that commit (see #49, #48, #47). This commit (dwightguth/nailgun@9386dea) served us quite well in our project for some time and continues to be used currently with minor modification (see yilongli/nailgun@d3e321a, which contains five commits that we cherry-picked to fix race conditions).

Recently I attempted to upgrade our version of nailgun to be a fork of #76, but unfortunately had to put that task on hold because it seems that something in between these two commits has had a very significant impact on the performance of a nailgun server running several concurrent processes. You can see my commit that is subject to the performance penalties at dwightguth/nailgun@c284046. Before I made the change of nailgun version, our `mvn verify` terminated on our build server in roughly  6 minutes with the longest-running integration test taking roughly 70 seconds to complete. Aftewards, the build started intermittently hitting its 10-minute timeout window, as well as throwing occasional OutOfMemoryErrors, and the increase in time spent running the same single program was over 100%, increasing to between 200 and 300 seconds.

Now it's possible that both situations are in some way due to GC thrashing and that modifying the GC settings will fix both errors. But even if that is the only source of the difference in performance, that would imply that some recent change to nailgun has significantly increased nailgun's memory footprint. I haven't done a lot of investigating of this issue, but it seems to affect both local and network sockets. I don't have any more time to devote to trying to figure this out at the moment, but @bhamiltoncx suggested I file an issue with the information in case someone would like to investigate. The project in question is github.com/kframework/k. I know people have had issues building it on some platforms, which I haven't had the time to fix yet, but you are welcome to try it out (to build, just run `mvn verify`).

**Comment by bhamiltoncx** [comment]
Could you list the supported configurations for that framework?

**Comment by dwightguth** [comment]
It has been tested on Ubuntu 14.04, Debian Jessie, Windows 7 and 10, and OSX Mavericks. It's possible other versions of these OSes will also work.

**Comment by sbalabanov** [comment]
Closing all issues older than 6 months; please reopen if it is still relevant
