### ISSUE TITLE
Static variables shared across instances

### ISSUE THREAD

**Issue by gmatht** [facebook/nailgun#90]
Run directly under normal java the following code just outputs "Hello, World". When run under nailgun it prints an increasing number of "Worlds" each time it is run. 

```
public class HelloWorld {
    static String x="Hello, ";
    public static void main(String[] args) {
        x=x+"World";
        System.out.println(x);
    }
}
```

I doubt this is a "code bug" that can be fixed, but is nevertheless a trap for the unwary that I think should be documented. It could also be documented that the main() function should be threadsafe as nailgun does not appear to serialize the requests but instead starts multiple threads at a time.

**Comment by jvican** [comment]
I bet this is fixed upstream, could be closed.
